#!/usr/bin/env ruby
#^syntax detection

# !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
# AFTER YOU CHANGE THIS FILE, RUN:
# librarian-chef install
# !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!


site 'http://community.opscode.com/api/v1'

# cookbook 'chef-client'
cookbook 'apt'
cookbook 'build-essential'
cookbook 'user'
cookbook 'ruby_build'
cookbook 'application_ruby'
cookbook 'nginx'
cookbook 'git'

cookbook 'rvm',
  :git => 'https://github.com/fnichol/chef-rvm'

# cookbook 'postgresql',
#   :git => 'https://github.com/findsyou/cookbooks',
#   :ref => 'postgresql-improvements'
